version: '3.9'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Password1@"
    ports:
        - "1433:1433"

  portfoliojay:
    image: ${DOCKER_REGISTRY-}portfoliojay
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
        - "8080:80"
